server:
  port: 8081
spring:
  application:
    name: reggie_take_out_front
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///2022_reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 100MB
  main:
    allow-circular-references: true

  #Redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0 #操作的是0号数据库
    lettuce:
      pool:
        max-idle: 4
        max-wait: 1ms
  cache:
    redis:
      time-to-live: 1800000M #设置缓存过期时间，可选


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

reggie:
  path: E:\reggie-project-dishpic\

#配置短信发送的配置
sms:
  signName: 黑马
  templateCode: SMS_133865179



